### ISSUE TITLE
Until Dawn Elf Relocation Error

### ISSUE THREAD

**Issue by illusionyy** [astrelsky/GhidraOrbis#1]
Dumped executable through app dumper, when loading into Ghidra with [newest release](https://github.com/astrelsky/GhidraOrbis/releases/tag/1.0.2) got the following errors:

**Edit:** ~~Seems to analyze fine~~ Throws this after analyze. Xref were found like usual and looks to be completely analyzed.
![image](https://user-images.githubusercontent.com/37698908/115136218-627fac80-a059-11eb-9cf0-1043239dd99a.png)

<details> 
<summary>Info</summary>

```
Skipping zero-length segment [.comment,null] at address OTHER:00000000
Skipping zero-length segment [.libversion,null] at address OTHER:00000000
Unsupported Thread-Local Symbol not loaded: JHvEnCQLPQI#x#w
Elf Relocation Error: Type = 16 (0x10) at 030e19f8, Symbol = JHvEnCQLPQI#x#w: TLS symbol relocation not yet supported
Elf Relocation Error: Type = 17 (0x11) at 030e1a00, Symbol = JHvEnCQLPQI#x#w: TLS symbol relocation not yet supported
Address range for 02f74e60, 03332498 is not contained in memory
ghidra.util.exception.NotFoundException: Address range for 02f74e60, 03332498 is not contained in memory
	at ghidra.program.database.module.ModuleManager.move(ModuleManager.java:566)
	at ghidra.program.database.module.FragmentDB.move(FragmentDB.java:168)
	at orbis.elf.blockmaker.ProgramReadOnlyBlockMaker.makeBlock(ProgramReadOnlyBlockMaker.java:58)
	at orbis.elf.OrbisElfExtension.processGotPlt(OrbisElfExtension.java:202)
	at orbis.elf.OrbisElfProgramBuilder.load(OrbisElfProgramBuilder.java:129)
	at orbis.elf.OrbisElfProgramBuilder.loadElf(OrbisElfProgramBuilder.java:48)
	at orbis.loader.GhidraOrbisElfLoader.load(GhidraOrbisElfLoader.java:82)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:400)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:349)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:88)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

</details>

**Comment by astrelsky** [comment]
TLS relocations aren't supported at all in Ghidra yet. The exception there is my fault though and I will investigate it when I can. That exception should only effect the creation of the named memory blocks and program fragments. You may need to manually find the start of the read only data section to split it and remove the executable flag in Ghidra. There is a lot of guess work involved and this is likely due to some unexpected edge case.

The warnings after analysis related to demangling can be ignored it's just garbage. Iirc the Ghidra dev's will be moving those warnings out of that message dialogue to prevent confusion as it gets reported a lot but there isn't actually a problem.

**Comment by astrelsky** [comment]
I just now saw the provided stack trace. I'll work on it.
