### ISSUE TITLE
Importing certain executable causes exception

### ISSUE THREAD

**Issue by illusionyy** [astrelsky/GhidraOrbis#10]
<details>
<summary>libSceVideoOut (Click to Expand)</summary>

```
----- Loading /D:/6.72/modules/system/common/lib/libSceVideoOut.sprx -----
Skipping zero-length segment [.tdata,Thread-Local Storage template] at address OTHER:00000000
Skipping zero-length segment [.libversion,null] at address OTHER:00000000
java.lang.NullPointerException
	at orbis.elf.blockmaker.ProgramReadOnlyBlockMaker.createTrampolines(ProgramReadOnlyBlockMaker.java:109)
	at orbis.elf.blockmaker.ProgramReadOnlyBlockMaker.makeBlock(ProgramReadOnlyBlockMaker.java:46)
	at orbis.elf.OrbisElfExtension.processGotPlt(OrbisElfExtension.java:202)
	at orbis.elf.OrbisElfProgramBuilder.load(OrbisElfProgramBuilder.java:129)
	at orbis.elf.OrbisElfProgramBuilder.loadElf(OrbisElfProgramBuilder.java:48)
	at orbis.loader.GhidraOrbisElfLoader.load(GhidraOrbisElfLoader.java:81)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

</details>

Todo: add more exes

**Comment by illusionyy** [comment]
Still an issue after https://github.com/astrelsky/GhidraOrbis/commit/1fdc37eb97c836432c0d664241e44963641d872d

<details>
<summary>libSceVideoOut (Click to Expand)</summary>

```
----- Loading /D:/6.72/modules/system/common/lib/libSceVideoOut.sprx -----
Skipping zero-length segment [.tdata,Thread-Local Storage template] at address OTHER:00000000
Skipping zero-length segment [.libversion,null] at address OTHER:00000000
java.lang.NullPointerException
    at ghidra.util.datastruct.RedBlackTree.getEntryLessThanEqual(RedBlackTree.java:85)
    at ghidra.program.model.address.AddressSet.contains(AddressSet.java:426)
    at ghidra.program.database.mem.MemoryMapDB.contains(MemoryMapDB.java:1750)
    at ghidra.program.database.module.ModuleManager.move(ModuleManager.java:565)
    at ghidra.program.database.module.FragmentDB.move(FragmentDB.java:145)
    at orbis.elf.blockmaker.ProgramReadOnlyBlockMaker.createTrampolines(ProgramReadOnlyBlockMaker.java:109)
    at orbis.elf.blockmaker.ProgramReadOnlyBlockMaker.makeBlock(ProgramReadOnlyBlockMaker.java:46)
    at orbis.elf.OrbisElfExtension.processGotPlt(OrbisElfExtension.java:202)
    at orbis.elf.OrbisElfProgramBuilder.load(OrbisElfProgramBuilder.java:129)
    at orbis.elf.OrbisElfProgramBuilder.loadElf(OrbisElfProgramBuilder.java:48)
    at orbis.loader.GhidraOrbisElfLoader.load(GhidraOrbisElfLoader.java:81)
    at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
    at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
    at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
    at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
    at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
    at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
    at ghidra.util.task.Task.monitoredRun(Task.java:134)
    at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)
```

</details>

**Comment by astrelsky** [comment]
@illusion0001 give it another shot. If it still results in an NPE the only thing I can think of atm is to catch it as I have no idea what could possibly be null.

**Comment by illusionyy** [comment]
fixed, btw what's with the lib not found message?
```
----- Loading /E:/DL/libSceVideoOut.sprx -----
Skipping zero-length segment [.tdata,Thread-Local Storage template] at address OTHER:00000000
Skipping zero-length segment [.libversion,null] at address OTHER:00000000
  [libSceAvSetting.prx] -> not found
  [libSceMbus.prx] -> not found
  [libkernel.prx] -> not found
  [libSceRegMgr.prx] -> not found
  [libSceSysmodule.prx] -> not found
  [libSceLibcInternal.prx] -> not found
```

**Comment by astrelsky** [comment]
> fixed, btw what's with the lib not found message?
> ```
> ----- Loading /E:/DL/libSceVideoOut.sprx -----
> Skipping zero-length segment [.tdata,Thread-Local Storage template] at address OTHER:00000000
> Skipping zero-length segment [.libversion,null] at address OTHER:00000000
>   [libSceAvSetting.prx] -> not found
>   [libSceMbus.prx] -> not found
>   [libkernel.prx] -> not found
>   [libSceRegMgr.prx] -> not found
>   [libSceSysmodule.prx] -> not found
>   [libSceLibcInternal.prx] -> not found
> ```

It's looking for the libraries in the same fashion that it does for dll and linux so. It's never going to find them but I'm not sure how to disable it.
