### ISSUE TITLE
java.lang.NullPointerException on import

### ISSUE THREAD

**Issue by kleingulo** [astrelsky/GhidraOrbis#11]
This happens on importing a specific ps4 .elf file.

Unexpected Error: java.lang.NullPointerException
ghidra.util.exception.AssertException: Unexpected Error: java.lang.NullPointerException
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:308)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:296)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.pruneDiscardableBlocks(DefaultElfProgramBuilder.java:167)
	at orbis.elf.OrbisElfProgramBuilder.load(OrbisElfProgramBuilder.java:109)
	at orbis.elf.OrbisElfProgramBuilder.loadElf(OrbisElfProgramBuilder.java:48)
	at orbis.loader.GhidraOrbisElfLoader.load(GhidraOrbisElfLoader.java:81)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.lambda$invoke$2(DefaultElfProgramBuilder.java:299)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:306)
	... 16 more

---------------------------------------------------
Build Date: 2021-Dec-21 1319 EST
Ghidra Version: 10.1.1
Java Home: C:\Program Files (x86)\jdk-11.0.12+7
JVM Version: Eclipse Foundation 11.0.12
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-034L5OG

**Comment by astrelsky** [comment]
@kleingulo may you check if c25dec02f50de0f9699e8d99576ff9d487216b1f fixed this please?

**Comment by kleingulo** [comment]
Hey, thanks for the update. Unfortunately it doesn't fix the problem.

Unexpected Error: java.lang.NullPointerException
ghidra.util.exception.AssertException: Unexpected Error: java.lang.NullPointerException
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:308)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:296)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.pruneDiscardableBlocks(DefaultElfProgramBuilder.java:167)
	at orbis.elf.OrbisElfProgramBuilder.load(OrbisElfProgramBuilder.java:109)
	at orbis.elf.OrbisElfProgramBuilder.loadElf(OrbisElfProgramBuilder.java:48)
	at orbis.loader.GhidraOrbisElfLoader.load(GhidraOrbisElfLoader.java:81)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.lambda$invoke$2(DefaultElfProgramBuilder.java:299)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:306)
	... 16 more

---------------------------------------------------
Build Date: 2021-Dec-21 1319 EST
Ghidra Version: 10.1.1
Java Home: C:\Program Files (x86)\jdk-11.0.12+7
JVM Version: Eclipse Foundation 11.0.12
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-034L5OG

**Comment by kleingulo** [comment]
Good news. On ghidra_10.0.2_PUBLIC it's working.

**Comment by astrelsky** [comment]
I've closed it as I know that specific issue is fixed. If you still have a problem just comment and I'll reopen it if you are unable to reopen it yourself.
