### ISSUE TITLE
10.3 rebuild

### ISSUE THREAD

**Issue by oknyshuk** [astrelsky/GhidraOrbis#19]
hey, please rebuild this for ghidra 10.2.3

**Comment by astrelsky** [comment]
Done (note it's untested)

**Comment by oknyshuk** [comment]
tested now, decompiled PS4 kernel with ghidra 10.2.3 using 1.0115 release extensions. thanks for fast answer!

**Comment by astrelsky** [comment]
> tested now, decompiled PS4 kernel with ghidra 10.2.3 using 1.0115 release extensions. thanks for fast answer!

If anything were to be broken it'd probably be loading a normal elf. Which I might not even fix :joy:

**Comment by oknyshuk** [comment]
I won't be using ghidra for anything but ps4 kernel anyway 😄

**Comment by oknyshuk** [comment]
what about ghidra 10.3? :)

**Comment by astrelsky** [comment]
> what about ghidra 10.3? :)

May you give this a shot please before I release it? It's been a while since I've touched this.

[ghidra_10.3_PUBLIC_20230515_GhidraOrbis.zip](https://github.com/astrelsky/GhidraOrbis/files/11477087/ghidra_10.3_PUBLIC_20230515_GhidraOrbis.zip)

Note the c++ class analyzer has problems so I recommend not having it installed.

**Comment by oknyshuk** [comment]
after installing this extension and trying to import PS4 kernel.bin as Orbis ELF I get an `Error importing file: kernel.bin` error:
```
This should never occur
ghidra.util.exception.AssertException: This should never occur
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:304)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:292)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.processGNU_readOnly(DefaultElfProgramBuilder.java:219)
	at orbis.elf.OrbisElfProgramBuilder.load(OrbisElfProgramBuilder.java:131)
	at orbis.elf.OrbisElfProgramBuilder.loadElf(OrbisElfProgramBuilder.java:48)
	at orbis.loader.GhidraOrbisElfLoader.load(GhidraOrbisElfLoader.java:77)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:809)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:100)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:388)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:347)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.setAccessible(boolean)" because "m" is null
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.lambda$invoke$2(DefaultElfProgramBuilder.java:295)
	at ghidra.app.util.opinion.DefaultElfProgramBuilder.invoke(DefaultElfProgramBuilder.java:302)
	... 16 more

---------------------------------------------------
Build Date: 2023-May-12 1514 CEST
Ghidra Version: 10.3
Java Home: /usr/lib/jvm/java-20-openjdk
JVM Version: N/A 20.0.1
OS: Linux 6.3.1-1-clear amd64
```

**Comment by astrelsky** [comment]
Oh I forgot about those ones.

**Comment by astrelsky** [comment]
[ghidra_10.3_PUBLIC_20230515_GhidraOrbis.zip](https://github.com/astrelsky/GhidraOrbis/files/11482139/ghidra_10.3_PUBLIC_20230515_GhidraOrbis.zip)

That should be fixed I think.

**Comment by oknyshuk** [comment]
yeah, that works

**Comment by astrelsky** [comment]
> yeah, that works

Great, I'll create a release tonight. Thank you.
