### ISSUE TITLE
java.io.IOException: Invalid index: 758841384 - Fails to import eboot.bin of Spiderman 1.05

### ISSUE THREAD

**Issue by chris-0xcd** [astrelsky/GhidraOrbis#9]
Trying to load a decrypted eboot.bin (using unself) gives:

Invalid index: 758841384
java.io.IOException: Invalid index: 758841384
	at ghidra.app.util.bin.FileByteProvider.ensureBounds(FileByteProvider.java:264)
	at ghidra.app.util.bin.FileByteProvider.readBytes(FileByteProvider.java:121)
	at ghidra.formats.gfilesystem.RefdByteProvider.readBytes(RefdByteProvider.java:91)
	at ghidra.app.util.bin.BinaryReader.readInt(BinaryReader.java:678)
	at ghidra.app.util.bin.BinaryReader.readNextInt(BinaryReader.java:315)
	at ghidra.app.util.bin.format.elf.ElfSectionHeader.initElfSectionHeader(ElfSectionHeader.java:110)
	at ghidra.app.util.bin.format.elf.ElfSectionHeader.createElfSectionHeader(ElfSectionHeader.java:95)
	at ghidra.app.util.bin.format.elf.ElfHeader.parseSectionHeaders(ElfHeader.java:905)
	at orbis.elf.OrbisElfHeader.parse(OrbisElfHeader.java:64)
	at orbis.elf.OrbisElfProgramBuilder.load(OrbisElfProgramBuilder.java:62)
	at orbis.elf.OrbisElfProgramBuilder.loadElf(OrbisElfProgramBuilder.java:48)
	at orbis.loader.GhidraOrbisElfLoader.load(GhidraOrbisElfLoader.java:81)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:347)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:83)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by astrelsky** [comment]
I will take a look tonight.

**Comment by astrelsky** [comment]
@chris-0xcd it seems you may not have a valid elf section header. Do you have a way to verify that the eboot was decrypted properly and the result is a valid elf?

This is where it is failing:

https://github.com/NationalSecurityAgency/ghidra/blob/7f2675c9c16bc42ac6a32e19b192d01d909cd388/Ghidra/Features/Base/src/main/java/ghidra/app/util/bin/format/elf/ElfHeader.java#L904

**Comment by chris-0xcd** [comment]
Very strange, I've now tried grabbing the eboot.bin directly from the PS4 using the built-in FTP of GoldHEN and the only differences seem to be that `e_shoff`, `e_shentsize`, `e_shnum` and `e_shstrndx` are all set to zero in the version from the PS4 but are set to (invalid?) values in the one decrypted with unfself.

```
Num. differences:  6
offset differs: 0x28
List of differences:
offset 0x00000028: 0x00 != 0x28 (  0 != '(')
offset 0x0000002a: 0x00 != 0x3b (  0 != ';')
offset 0x0000002b: 0x00 != 0x2d (  0 != '-')
offset 0x0000003a: 0x00 != 0x40 (  0 != '@')
offset 0x0000003c: 0x00 != 0x28 (  0 != '(')
offset 0x0000003e: 0x00 != 0x25 (  0 != '%')
```

Interesting enough packaging up the decrypted eboot.bin with the invalid values and installing the .pkg still allows the game to run. Not really sure what's going on, but clearly not an issue with GhidraOrbis. Sorry for wasting your time...
